name: News Fetcher

on:
  schedule:
    # IST (UTC+5:30) conversions:
    # 7:00 AM IST = 1:30 AM UTC
    # 1:00 PM IST = 7:30 AM UTC
    # 7:00 PM IST = 1:30 PM UTC
    - cron: '30 1,7,13 * * *'  # Runs at 7 AM, 1 PM, and 7 PM IST
  workflow_dispatch:  # Allows manual trigger

jobs:
  parse-rss-data:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests 

    - name: Run RSS parser
      run: python news_fetch.py

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Commit and push if changes
      run: |
        git add data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feed data [automated]" && git push || echo "Push failed. Changes are committed locally.")
