name: Generate UPSC Quiz

on:
  schedule:
    - cron: '30 1 * * *'  # Runs daily at 1:30 AM UTC
  workflow_dispatch:

jobs:
  generate_quiz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 openai pandas

      - name: Run quiz generation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use the GitHub secret as an environment variable
        run: |
          python openai_gen.py  # Replace with your script name

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        run: |
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-generate quiz for $(date +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi  # End of the if block
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

